plugins:
    - rubocop-minitest
    - rubocop-performance
    - rubocop-rake
    - rubocop-thread_safety

AllCops:
    TargetRubyVersion: '3.2'
    NewCops: enable

# Metrics are too arbitrary.
Metrics/AbcSize:
    Enabled: false
Metrics/ClassLength:
    Enabled: false
Layout/LineLength:
    Enabled: false
Metrics/MethodLength:
    Enabled: false

Naming/PredicateMethod:
    AllowedMethods:
        - main

# Weird.
Style/FormatStringToken:
    Enabled: false
Style/NumericPredicate:
    Enabled: false

# Trailing commas are good.
Style/TrailingCommaInArguments:
    Enabled: false
Style/TrailingCommaInArrayLiteral:
    Enabled: false
Style/TrailingCommaInHashLiteral:
    Enabled: false

Gemspec/DevelopmentDependencies:
    Enabled: false

# Sometimes it makes sense to have lots of assertions.
Minitest/MultipleAssertions:
    Enabled: false
